### ISSUE TITLE
[UX] Merge Quiz-wise Regrade and User-wise Regrade

### ISSUE THREAD

**Issue by ankitjavalkar** [FOSSEE/online_test#553] opened 2019-01-23 10:11 UTC
Within the regrade feature available at ```/exam/manage/grader/``` the Quiz-wise regrade and User-wise regrade essentially display the same information and provide the same functionality.

Both options can be merged into one by providing a Quiz, a User and an Attempt Number Filter.

**Comment by adityacp** [comment] 2020-03-11 04:42
Closing this as the issue is mentioned in #614

**Closed by adityacp** 2020-03-11 04:42 UTC
